//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deavnote.app.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("deavnote.app.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time entry name.
        /// </summary>
        internal static string AddTimeEntryView_EntryName_Placeholder {
            get {
                return ResourceManager.GetString("AddTimeEntryView_EntryName_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Optional description.
        /// </summary>
        internal static string AddTimeEntryView_EntryWorkDone_Placeholder {
            get {
                return ResourceManager.GetString("AddTimeEntryView_EntryWorkDone_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the time entry will be linked to this task.
        /// </summary>
        internal static string AddTimeEntryView_LinkedToExistingTask_Banner {
            get {
                return ResourceManager.GetString("AddTimeEntryView_LinkedToExistingTask_Banner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can link this time entry to an existing task or create a new one.
        /// </summary>
        internal static string AddTimeEntryView_NoTaskSelected_Banner {
            get {
                return ResourceManager.GetString("AddTimeEntryView_NoTaskSelected_Banner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Related Task.
        /// </summary>
        internal static string AddTimeEntryView_RelatedTask_Title {
            get {
                return ResourceManager.GetString("AddTimeEntryView_RelatedTask_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. DEV-168.
        /// </summary>
        internal static string AddTimeEntryView_TaskCode_Placeholder {
            get {
                return ResourceManager.GetString("AddTimeEntryView_TaskCode_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to e.g. DO-896.
        /// </summary>
        internal static string AddTimeEntryView_TaskName_Placeholder {
            get {
                return ResourceManager.GetString("AddTimeEntryView_TaskName_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The task will be created.
        /// </summary>
        internal static string AddTimeEntryView_TaskWillBeCreated_Banner {
            get {
                return ResourceManager.GetString("AddTimeEntryView_TaskWillBeCreated_Banner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time Entry.
        /// </summary>
        internal static string AddTimeEntryView_TimeEntry_Title {
            get {
                return ResourceManager.GetString("AddTimeEntryView_TimeEntry_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string Common_CreatedAt {
            get {
                return ResourceManager.GetString("Common_CreatedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Common_Duration {
            get {
                return ResourceManager.GetString("Common_Duration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified at.
        /// </summary>
        internal static string Common_ModifiedAt {
            get {
                return ResourceManager.GetString("Common_ModifiedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started at.
        /// </summary>
        internal static string Common_StartedAt {
            get {
                return ResourceManager.GetString("Common_StartedAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work done.
        /// </summary>
        internal static string Common_WorkDone {
            get {
                return ResourceManager.GetString("Common_WorkDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a task description here....
        /// </summary>
        internal static string DevTaskDetailView_Description_Placeholder {
            get {
                return ResourceManager.GetString("DevTaskDetailView_Description_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add time entry.
        /// </summary>
        internal static string JournalView_AddTimeEntry_Tooltip {
            get {
                return ResourceManager.GetString("JournalView_AddTimeEntry_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy today&apos;s time entries.
        /// </summary>
        internal static string JournalView_CopyTodayEntries_Tooltip {
            get {
                return ResourceManager.GetString("JournalView_CopyTodayEntries_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go to next day.
        /// </summary>
        internal static string JournalView_GoToNextDay_Tooltip {
            get {
                return ResourceManager.GetString("JournalView_GoToNextDay_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go to previous day.
        /// </summary>
        internal static string JournalView_GoToPreviousDay_Tooltip {
            get {
                return ResourceManager.GetString("JournalView_GoToPreviousDay_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go to today.
        /// </summary>
        internal static string JournalView_GoToToday_Tooltip {
            get {
                return ResourceManager.GetString("JournalView_GoToToday_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to deavnote.app.
        /// </summary>
        internal static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchView_Watermark {
            get {
                return ResourceManager.GetString("SearchView_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        internal static string TimeEntryDetailView_Cancel_Tooltip {
            get {
                return ResourceManager.GetString("TimeEntryDetailView_Cancel_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string TimeEntryDetailView_Save_Tooltip {
            get {
                return ResourceManager.GetString("TimeEntryDetailView_Save_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter what was done for this time entry....
        /// </summary>
        internal static string TimeEntryDetailView_WorkDone_Placeholder {
            get {
                return ResourceManager.GetString("TimeEntryDetailView_WorkDone_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy time entry.
        /// </summary>
        internal static string TimeEntryListItemView_Copy_Tooltip {
            get {
                return ResourceManager.GetString("TimeEntryListItemView_Copy_Tooltip", resourceCulture);
            }
        }
    }
}
