<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\deavnote.repository\deavnote.repository.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EditorConfigFiles Remove="C:\Workspaces\deavnote\deavnote.core\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<None Include="C:\Workspaces\deavnote\deavnote.core\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Meziantou.Analyzer" Version="3.0.108">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
